### Create Sherlock File from matfile

In [3]:
import numpy as np
import os

In [4]:
PATH="/home/musaup/Downloads/NeuralNetwork7_3.mat"

In [5]:
def load_nn_mat_file(nn_source_dir,file_name):
    import scipy.io as sio
    import os
    if(file_name.endswith(".mat")):
        path=os.path.join(nn_source_dir,file_name)
        mat_contents=sio.loadmat(path,squeeze_me=True)
        del mat_contents['__header__']
        del mat_contents['__version__']
        del mat_contents['__globals__']
        nn_info={}
        network_weights=mat_contents['W']
        network_biases=mat_contents['b']
        del mat_contents['W']
        del mat_contents['b']
        for item in mat_contents.keys():
            nn_info[item]=mat_contents[item]
    else:
        print("File specified is not a .mat file. Please check the directory path")
        return None
    return nn_info, network_weights, network_biases

In [7]:
nn_info, network_weights, network_biases=load_nn_mat_file('/home/musaup/Downloads','NeuralNetwork7_3.mat')

In [33]:
network_weights[7].shape

(2, 7)

In [9]:
network_biases

array([array([-1.65777807, -0.42031465, -1.878918  ,  0.26349022, -2.42948357,
       -0.52866133,  2.71314475]),
       array([ 1.73961725,  0.96154161,  0.27516898,  1.23075651,  0.49898044,
        1.08298651, -1.19933006]),
       array([-1.66536974,  0.19819551,  2.08863383, -0.49908468, -0.59362813,
       -1.05973936,  0.38393256]),
       array([-0.6781979 , -1.08362035, -0.63793228,  2.45161022,  0.09794752,
        0.14564606, -0.51656124]),
       array([-0.4366133 ,  0.50735753,  0.25836082,  0.57519252, -0.21806075,
       -0.58741641, -0.25165288]),
       array([ 1.70569624, -1.01138053,  0.21329293,  1.29031081, -0.01182289,
        1.27309308,  0.42802656]),
       array([ 0.34645532, -1.32114763,  1.31073279, -2.9799614 ,  0.12145654,
        0.84859308, -1.04093185]),
       array([-1.34736256, -0.50408875])], dtype=object)

In [10]:
network_biases.shape

(8,)

In [11]:
network_biases[0]

array([-1.65777807, -0.42031465, -1.878918  ,  0.26349022, -2.42948357,
       -0.52866133,  2.71314475])

In [12]:
file = open('/home/musaup/Documents/Research/sherlock.txt','w') 

In [71]:
network_biases[0]

array([-1.65777807, -0.42031465, -1.878918  ,  0.26349022, -2.42948357,
       -0.52866133,  2.71314475])

In [89]:
def create_sherlock_file(source_dir,sourcefile, destination, filename):
    nn_info, network_weights, network_biases=load_nn_mat_file(source_dir,sourcefile)
    file=open(os.path.join(destination,filename)+'.txt','w')
    numberOfInputs=network_weights[0].shape[1]
    numberOfLayers=len(network_weights)
    numberOfOutputs=network_weights[len(network_weights)-1].shape[0]
    file.write(str(numberOfInputs)+'\n')
    file.write(str(numberOfOutputs)+'\n')
    file.write(str(numberOfLayers)+'\n')
    for item in range(0,numberOfLayers):
        file.write(str(network_weights[item].shape[0])+'\n')
    #for item in range(0,numberOfLayers-1):
        #print(network_weights[item].shape[0])
    for layer in range(0,numberOfLayers):
        for row in range(0,len(network_weights[layer])):
            for weight in range(0,len(network_weights[layer][row])):
                file.write(str(network_weights[layer][row][weight])+'\n')
            file.write(str(network_biases[layer][row])+'\n')
    file.close()
            
        
    

In [88]:
PATH="/home/musaup/Downloads"
sourcefile='NeuralNetwork7_3.mat'
DEST='/home/musaup/Documents/Research'
create_sherlock_file(PATH,sourcefile,DEST,'sherlock_1')

In [49]:
network_weights[0][1:4]

array([[-2.23267186, -0.54702192,  0.48569948],
       [-1.55805817,  1.76128243, -0.53598228],
       [ 1.7777791 , -0.60650664, -0.9761681 ]])